[package]
org = "himasha_valantina"
name = "healthRecords"
version = "0.1.0"
distribution = "2201.12.7"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "mongodb"
version = "5.1.0"

[[dependency]]
org = "ballerina"
name = "uuid"
version = "1.0.0"